seperate jobs

diff --git a/.github/workflows/terraform-apply.yml b/.github/workflows/terraform-apply.yml
--- a/.github/workflows/terraform-apply.yml
+++ b/.github/workflows/terraform-apply.yml
@@ -63,56 +63,56 @@ jobs:
     - name: Terraform Plan
       id: plan
       # if: github.event_name == 'pull_request'
-      continue-on-error: true
+      # continue-on-error: true
       run: terraform plan -no-color -compact-warnings
        # -out myoutfile.out
 
-    # Terraform Plan Status returns whether a plan was successfully generated or not. This step highlights whenever a plan fails because the "Terraform Plan" step continues on error.
-    - name: Terraform Plan Status
-      if: steps.plan.outcome == 'failure'
-      run: exit 1
-
-    # Update Pull Request adds a comment to the pull request with the results of the format, init and plan steps. In addition, it displays the plan output (steps.plan.outputs.stdout). This allows your team to review the results of the plan directly in the PR instead of opening Terraform Cloud. This step only runs on pull requests.
-
-    - name: token
-      run: |
-        echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
-        echo "event_name: ${{ github.event_name }}"
-        echo "event_number: ${{ github.event_number }}"
-        echo "event.number: ${{ github.event.number }}"
-
-
-    - name: Update Pull Request
-      uses: actions/github-script@0.9.0
-      # if: github.event_name == 'pull_request'
-      env:
-        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-      with:
-        github-token: ${{ secrets.GITHUB_TOKEN }}
-        script: |
-          const output = `#### Terraform Format and Style 🖌\`${{ steps.format.outcome }}\`
-          #### Terraform Check ⚙️\`${{ steps.check.outcome }}\`
-          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-          <details><summary>Show Plan</summary>
-          \`\`\`${process.env.PLAN}\`\`\`
-          </details>
-          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
-
-          github.issues.createComment({
-            issue_number: 1,
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-            body: output
-          })
-
-    # Terraform Apply applies the configuration. This step will only run when a commit is pushed to master.
+    # # Terraform Plan Status returns whether a plan was successfully generated or not. This step highlights whenever a plan fails because the "Terraform Plan" step continues on error.
+    # - name: Terraform Plan Status
+    #   if: steps.plan.outcome == 'failure'
+    #   run: exit 1
+    #
+    # # Update Pull Request adds a comment to the pull request with the results of the format, init and plan steps. In addition, it displays the plan output (steps.plan.outputs.stdout). This allows your team to review the results of the plan directly in the PR instead of opening Terraform Cloud. This step only runs on pull requests.
+    #
+    # - name: token
+    #   run: |
+    #     echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
+    #     echo "event_name: ${{ github.event_name }}"
+    #     echo "event_number: ${{ github.event_number }}"
+    #     echo "event.number: ${{ github.event.number }}"
+    #
+    #
+    # - name: Update Pull Request
+    #   uses: actions/github-script@0.9.0
+    #   # if: github.event_name == 'pull_request'
+    #   env:
+    #     PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+    #   with:
+    #     github-token: ${{ secrets.GITHUB_TOKEN }}
+    #     script: |
+    #       const output = `#### Terraform Format and Style 🖌\`${{ steps.format.outcome }}\`
+    #       #### Terraform Check ⚙️\`${{ steps.check.outcome }}\`
+    #       #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+    #       #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+    #       <details><summary>Show Plan</summary>
+    #       \`\`\`${process.env.PLAN}\`\`\`
+    #       </details>
+    #       *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+    #
+    #       github.issues.createComment({
+    #         issue_number: 1,
+    #         owner: context.repo.owner,
+    #         repo: context.repo.repo,
+    #         body: output
+    #       })
+    #
+    # # Terraform Apply applies the configuration. This step will only run when a commit is pushed to master.
+    # # - name: Terraform Apply
+    # #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
+    # #   run: terraform apply -auto-approve
     # - name: Terraform Apply
     #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
-    #   run: terraform apply -auto-approve
-    - name: Terraform Apply
-      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
-      run: echo terraform apply -auto-approve
+    #   run: echo terraform apply -auto-approve
 
 
     - name: Print Environment
@@ -123,28 +123,28 @@ jobs:
       run: |
         find .
 
-  # apply-terraform:
-  #   if: ${{ always() }}
-  #   runs-on: ubuntu-latest
-  #   environment: 'approve-plan'
-  #
-  #   # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
-  #   defaults:
-  #     run:
-  #       shell: bash
-  #
-  #   steps:
-  #
-  #   - name: Print Environment
-  #     run: |
-  #       env | sort
-  #
-  #   - name: List Directory
-  #     run: |
-  #       find .
-  #
-  #     # On push to master, build or change infrastructure according to Terraform configuration files
-  #     # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
-  #   # - name: Terraform Apply
-  #   #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
-  #   #   run: terraform apply -auto-approve
+  apply-terraform:
+    if: ${{ always() }}
+    runs-on: ubuntu-latest
+    environment: 'approve-plan'
+
+    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
+    defaults:
+      run:
+        shell: bash
+
+    steps:
+
+    - name: Print Environment
+      run: |
+        env | sort
+
+    - name: List Directory
+      run: |
+        find .
+
+      # On push to master, build or change infrastructure according to Terraform configuration files
+      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
+    # - name: Terraform Apply
+    #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
+    #   run: terraform apply -auto-approve
