upadte

diff --git a/.github/workflows/terraform-destroy.yml b/.github/workflows/terraform-destroy.yml
--- a/.github/workflows/terraform-destroy.yml
+++ b/.github/workflows/terraform-destroy.yml
@@ -55,13 +55,17 @@ jobs:
     - name: Terraform Check
       run: terraform fmt -recursive -check
 
+    - name: PRINT
+      run: |
+        find . -type f
+
     # Generates an execution destroy for Terraform
-    - name: Terraform Plan
+    - name: Terraform Destroy
       id: destroy
       continue-on-error: true
       run: terraform destroy -auto-approve
        # -out myoutfile.out
 
-    - name: Terraform Plan Status
-      if: steps.destroy.outcome == 'failure'
-      run: exit 1
+    # - name: Terraform Plan Status
+    #   if: steps.destroy.outcome == 'failure'
+    #   run: exit 1
